[package]
name = "dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
serde_json = "1.0"
serde_with = { version = "2.3.3", features = ["base64"] }
serde = { version = "1.0.163", features = ["derive"] }
base64 = "0.21.0"