version: '3'
services:
  safeblog:
    build: .
    container_name: safeblog
    ports:
      - "80:8080"
    environment:
      - UWSGI_INI=/home/ctf/uwsgi.ini
      - NGINX_MAX_UPLOAD=1m
      - LISTEN_PORT=8080
    restart: always
